name: Deploy to Digital Ocean

on:
  push:
    branches: [master]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: hallee/eslint-action@1.0.3
  #       with:
  #         repo-token: ${{secrets.GITHUB_TOKEN}}
  deploy-to-production:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: rm -rf twid-server && git clone git@github.com:twid-chat/twid-server.git && cd twid-server && yarn && pm2 restart 0 && pm2 restart 1
